### ISSUE TITLE
empty when php7, wp 4.7, wp-realtime-sitemap 1.5.6

### ISSUE THREAD

**Issue by xiuxiu** [adamcoulombe/wp-realtime-sitemap#1]
Hi,

I am new to this plugin.

It doesn't work on my site 
http://dev.tech4k.com/index.php/sitemap/

also It works fine when wp-realtime-sitemap 1.5.1.

Please help.

Regards

**Comment by adamcoulombe** [comment]
you should download it from the official site. This is not an official repo

https://wordpress.org/plugins/wp-realtime-sitemap/

**Comment by xiuxiu** [comment]
Hi,

The link is just one demo site for show the tissue.

I downloaded the plugin from the official site.
